---
- name: Assign SCC to Service Account
  command: oc adm policy add-scc-to-user {{ scc_binding_item.scc }} -z {{ scc_binding_item.name }} -n {{ scc_binding_item.namespace }}
  when: scc_binding_item.scc is defined
  with_items: "{{ scc_binding_items }}"
  loop_control:
    loop_var: scc_binding_item
