---
- name: Assign SCC to Service Account
  command: oc adm policy add-scc-to-user {{ ar_os_scc_binding_item.scc }} -z {{ ar_os_scc_binding_item.name }} -n {{ ar_os_scc_binding_item.namespace }}
  when: ar_os_scc_binding_item.scc is defined
  with_items: "{{ ar_os_scc_binding_items }}"
  loop_control:
    loop_var: ar_os_scc_binding_item
