---
- name: Include assign-scc tasks for each item
  include_tasks: assign-scc.yml
  when: ar_os_scc_binding_item.scc is defined
  with_items: "{{ ar_os_scc_binding_items }}"
  loop_control:
    loop_var: ar_os_scc_binding_item
